---
kind: pipeline
name: deploy

clone:

steps:
  - name: deploy_schemas
    image: debian:stable-slim
    environment:
      schema_key:
        from_secret: schema_key
      schema_user:
        from_secret: schema_user
      schema_host:
        from_secret: schema_host
      schema_target:
        from_secret: schema_target
    commands:
      - apt update && apt install -y rclone openssh-client
      - mkdir -p ~/.ssh
      - eval $(ssh-agent -s)
      - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
      - echo "$schema_key" > ~/.ssh/id_rsa
      - chmod 600 ~/.ssh/id_rsa
      - ssh-add
      - rclone config create schema sftp host $schema_host user $schema_user port 22 use_insecure_cipher true disable_hashcheck true
      - rclone sync . schema:$schema_target -v --include "*.xsd" --include "*.json"

trigger:
  branch:
    - master
  event:
    - push

---
kind: signature
hmac: 28e1f0ec2f7c2fbff1cc82a925c1e9c629cdbce42ef0e65c70b98759f16401cf

...
