---
kind: pipeline
name: deploy

clone:

steps:
  - name: deploy_schemas
    image: joomlaprojects/docker-images:packager
    environment:
      schema_key:
        from_secret: schema_key
      schema_user:
        from_secret: schema_user
      schema_host:
        from_secret: schema_host
      schema_target:
        from_secret: schema_target
      RINGCENTRAL_WEBHOOK:
        from_secret: notification_url
    commands:
      - mkdir -p ~/.ssh
      - eval $(ssh-agent -s)
      - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
      - echo "$schema_key" > ~/.ssh/id_rsa
      - chmod 600 ~/.ssh/id_rsa
      - ssh-add
      - rclone config create schema sftp host $schema_host user $schema_user port 22 use_insecure_cipher true disable_hashcheck true
      - rclone sync . schema:$schema_target -v --include "*.xsd" --include "*.json"
      - /bin/notify

trigger:
  branch:
    - master
  event:
    - push

---
kind: signature
hmac: 84da7373285199103424f8c5e4dccece3cf2ebea928813d998c895799f6663b5

...
